# Generated by Django 5.1.5 on 2025-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1, "First Year"),
                            (2, "Second Year"),
                            (3, "Third Year"),
                            (4, "Fourth Year"),
                        ]
                    ),
                ),
                ("staff_name", models.CharField(max_length=255)),
                ("question_paper", models.FileField(upload_to="question_papers/")),
                ("answer_key", models.FileField(upload_to="answer_keys/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
