# Generated by Django 5.1.5 on 2025-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("CAT1", "CAT 1"), ("CAT2", "CAT 2")],
                default="CAT1",
                max_length=4,
            ),
        ),
    ]
