# Generated by Django 5.1.5 on 2025-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_exam_exam_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmission",
            name="answer_sheet",
            field=models.FileField(blank=True, null=True, upload_to="answer_sheets/"),
        ),
    ]
