# Generated by Django 5.1.5 on 2025-03-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_examsubmission_exam_evaluationresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsubmission",
            name="exam",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.exam"
            ),
            preserve_default=False,
        ),
    ]
