# Generated by Django 5.1.5 on 2025-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_evaluationresult_json_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name to identify the API key (e.g., Google, OpenAI).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("key", models.TextField(help_text="The actual API key string.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the key is currently in use.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="examsubmission",
            name="year",
            field=models.CharField(
                choices=[
                    (1, "First Year"),
                    (2, "Second Year"),
                    (3, "Third Year"),
                    (4, "Fourth Year"),
                ],
                max_length=1,
            ),
        ),
    ]
